# .octocov.yml Go example
coverage:
  paths:
    - apps/*/coverage/lcov.info
    - packages/*/coverage/lcov.info
codeToTestRatio:
  code:
    - '**/*.dart'
    - '!**/*_test.dart'
  test:
    - '**/*_test.dart'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}